### ISSUE TITLE
OptimisticLockException when saving a model the second time with joda DateTime and mysql 5.6

### ISSUE THREAD

**Issue by excepttheweasel** [ebean-orm/avaje-ebeanorm#236]
We have an ebean model like so:

    public class MyModel {
        public DateTime createdOn = DateTime.now()

This saves fine the first time (i.e. an insert), but when we update it we get an OptimisticLockException.

If however, we clear the millis component of createdOn, it works. e.g:

    @Override
    public void save() {
        this.createdOn = this.createdOn.minusMillis(this.createdOn.getMillisOfSecond());
        super.save();
    }

It looks like at the MySQL level, if you insert a timestamp with millis, it rounds the millis up. But when you select a field with millis it truncates. This is new behavior for 5.6, ebean appeared to work fine for 5.5. You can fix this by casting as a datetime at the query level. 

It seems to me that it might be possible for eBean to serialize date time objects with millisecond/microsecond precision and round up to the nearest second when using mysql datetime fields. Conversely if datetime(6) is being used do no rounding. Is that possible?

**Comment by rbygrave** [comment]
What version of Ebean are you using?  createdOn is not annotated with
@Version so it looks like you are using Ebean version 3.x - is that the
case?

**Comment by rbygrave** [comment]
More specifically:

1)  ... public DateTime createdOn = DateTime.now() is not what I'd consider
an ideal way to do this and instead expect users to use @CreatedTimestamp,
@UpdatedTimestamp or @Version. In this case I'd expect:
@CreatedTimestamp
public DateTime createdOn;

... and the setting of the createdOn value is left up to Ebean (which could
then look to truncate the millis for mysql).

2) In Ebean 4.x on the @Version column is used for optimistic concurrency
checking and ConcurrencyMode.ALL was dropped (and that means a createdOn
timestamp would never be used in for optimistic concurrency checking).

**Comment by excepttheweasel** [comment]
Using ```com.typesafe.play:play-java-ebean:2.3.7``` which looks quite old. Does @CreatedTimestamp/@UpdatedTimestamp work against joda DateTime in newer versions? Because that would certainly help.

**Comment by rbygrave** [comment]
*> which looks quite old.*

Yes, that is old now. My understanding is that Play 2.4 should support
Ebean 4.x.


*> Does @CreatedTimestamp/@UpdatedTimestamp work against joda DateTime in
newer versions? Because that would certainly help.*

I'd need to confirm but from memory I think yes.  With the recent work that
added support for java 8 dateTime types to Ebean 4.x there was an
associated change to support those types with @CreatedTimestamp etc and
that should have additionally covered any type that is convertable to
Timestamp (so that includes the relevant Joda types). So I think the answer
is yes but need to confirm that by looking at the commits/code etc.

**Comment by excepttheweasel** [comment]
1) ... and the setting of the createdOn value is left up to Ebean (which could
then look to truncate the millis for mysql).

This makes my models less useful if they're also being passed to say Jackson for JSON serialization or other systems where millis are useful. What I'd really like is to be able to strip millis only when persisting to MySQL.

2) I'd need to confirm but from memory I think yes.  With the recent work that added support for java 8 dateTime types to Ebean 4.x there was an associated change to support those types with @CreatedTimestamp etc and that should have additionally covered any type that is convertable to
Timestamp (so that includes the relevant Joda types).

Hmm, sadly it's not supported in 3.3.3 which is likely about as far as I'm going to be able to upgrade. Since this is only really a problem in testing code right now I'll stick to refresh() between saves. Pending some way to control column serialization.

**Comment by rbygrave** [comment]
BTW: The issue with MySql 5.6.4 can be resolved by using datetime(6) rather than datetime for the column definition as per http://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html

So in that respect the 'fix' for this issue is to change the DDL generation to generate datetime(6) rather than just datetime.

**Comment by rbygrave** [comment]
So TestJodaInsertUpdate passing with MySql 5.6.4 using the fix above.

So to me this is fixed in the next release which will be 4.5.5.

**Comment by ossd** [comment]
This patch brakes compatibility with MySql-5.5 that not supports "datetime(6)". Is it possible to make it configurable?
