### ISSUE TITLE
find method is returning old entity rather than updated entity in some situations.  [OR] Stateless updates should clear persistence context once executed. 

### ISSUE THREAD

**Issue by twilek** [ebean-orm/avaje-ebeanorm#237]
This problem is a little hard to explain in words so I will show it with code instead.

If I run this code the assert will succeed

    server.beginTransaction();
    
    UserEntity newUser = new UserEntity();
    newUser.setId("anyUserId");
    newUser.setEmail("any@email.com");
    server.save(newUser);
    
    UserEntity updateUser = new UserEntity();
    updateUser.setId("anyUserId");
    updateUser.setEmail("anyNew@email.com");
    server.update(updateUser);
    
    UserEntity loadedUser = server.find(UserEntity.class, "anyUserId");
    assertThat(loadedUser.getEmail(), is("anyNew@email.com"));
    
    server.rollbackTransaction();

But if I add one more find  between the save and the update the assert will fail

    server.beginTransaction();
    
    UserEntity newUser = new UserEntity();
    newUser.setId("anyUserId");
    newUser.setEmail("any@email.com");
    server.save(newUser);
    
    UserEntity dummyLoadedUser = server.find(UserEntity.class, "anyUserId"); // This row is added
    
    UserEntity updateUser = new UserEntity();
    updateUser.setId("anyUserId");
    updateUser.setEmail("anyNew@email.com");
    server.update(updateUser);
    
    UserEntity loadedUser = server.find(UserEntity.class, "anyUserId");
    assertThat(loadedUser.getEmail(), is("anyNew@email.com")); // This now fails
    
    server.rollbackTransaction();

The reason why I do the update by creting a new entity instead of using the loaded entity is because I try to mimick the behaviour of a mapping beteen a dto and an entity (I am using modelmapper in the real production code).

It also only seems to be a problem as long as I run the whole code block within one transaction.

I'm using ebean 4.5.3.

**Comment by rbygrave** [comment]
So the reason is that the last query is finding the instance in the
'persistence context'.  By default Ebean uses 'transaction scoped
persistence context'.

To get around this the second query could have used:
 .setPersistenceContextScope(QUERY) like:

    UserEntity loadedUser = getServer().find(UserEntity.class)

        .setPersistenceContextScope(QUERY)

        .setId("anyUserId")

        .findUnique();


Does that work for your scenario?


Thanks, Rob.

**Comment by twilek** [comment]
To add `.setPersistenceContextScope(QUERY)` works but it really doesn't make sense to me. Everything is already running within the same transaction, also the last find query, so I really don't understand why I shall need to add this to the find method. The correct behavior should rather be that the `server.update(updateUser)` adds the updated user to the persistence context, or clear the context for the user, so the next find will find in the same transaction finds the correct user object.

In the real world scenario we are wrapping all our calls to ebean in a repository class where we have general methods for this that we uses everywhere. We for example have a `UserRepostiroy` with a `get(String userId)` method, a `getByEmail(String email)`, a `update(User user)` method and so on. We can call these methods in any order and if we shall be able to avoid this behavior in all our cases we will then have to add `.setPersistenceContextScope(QUERY)` to every find method in our code, and I guess that will give us some other implications?

**Comment by rbygrave** [comment]
Hmmm, hang on.  So to be more specific ... I think this issue could perhaps be described as:
... the 'stateless update' could (or should) either:
a) update a matching bean if it is in the persistence context
b) clear a matching bean from the persistence context

That is, the way your 'repository' works is to use the 'stateless update' feature (rather than holding the same instance and updating that) ... and in this way you'd really like matching beans in the persistence context to be updated/cleared.

So given that I'll do some thinking and look at the code.  In short, I can see why this could be considered a bug for this type of use ... so I need to ponder if ALL stateless updates should in fact do this (say clear any matching bean from the persistence context if it exists and do this at statement execution rather than at commit time (much like delete)).

Ok, I'll have a look at that.

**Comment by twilek** [comment]
Ok, thanks. In the meenwhile I have added this to all our update, save and delete methods and it seems to fix our problem for now

    if(transaction instanceof SpiTransaction){
        SpiTransaction spiTransaction = (SpiTransaction) transaction;
        spiTransaction.getPersistenceContext().clear(beanType, id);
    }

**Comment by rbygrave** [comment]
Ok, I'm happy that this is a bug.  Specifically a 'stateless update' should clear the persistence context as soon as it is successfully executed (just like delete).  

Note that 'normal' bean updates don't need to clear the persistence context as the same instance is used. So the 'fix' for this issue is specific to stateless updates.

I created a test case based on the code above, reproduced the problem and confirmed the fix.  So I'm happy that this should resolve the issue you hit.

> I have added this to all our update, save and delete methods

So, I'm happy that you would not have had a problem with inserts or 'non-stateless' updates or deletes (as deletes already had code/behaviour to clear their beans from the persistence context just after they are executed).

So yes, in the next release you should not require your workaround as you have it above.
