### ISSUE TITLE
WriteJson not write Transient properties

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#276]
WriteJson not write Transient properties, how to wirte?

**Comment by icode** [comment]
@rbygrave I'm try to use ";transientInternalFields=true", but not useful

**Comment by icode** [comment]
i find issue, because avaje-ebeanorm-json set a null pathPoperties.
can add a method open or close write Transient properties?

**Comment by rbygrave** [comment]
I think this is a good example of why creating a failing testcase is a very good way to describe the problem/issue.

> i find issue, because avaje-ebeanorm-json set a null pathPoperties.

I don't think do. Specifically I think this problem is actually in WriteJson in that it uses the same isIncludeProperty() method for both @Transient and persistent properties.  The problem I believe is that @Transient properties will not return true at line 107: currentBean._ebean_getIntercept().isLoadedProperty(prop.getPropertyIndex());

... because they are not loaded from the DB ... hence transient properties are not ouput in the JSON unless they are explicitly specified to do so via 'path properties' (and I suspect you aren't using that).

As a testcase example, com.avaje.tests.text.json.TestTextJsonSimple outputs JSON for Customer entity bean which has 'selected' as a @Transient property ... and the 'selected' property is not in the JSON output by default.

**Comment by icode** [comment]
ok, I'm fork ebean-jackson module,and change for jax-rs call pathProperty

**Comment by rbygrave** [comment]
Well that is one approach.  However, I have created a failing test for this problem as I understand it ... and have a fix for it.  I'll push that up and you can see if the tests cover you use case.

If the tests I have added (and the fix I've made) do not cover your use case ... then I'd be interested to see your failing test case to try and understand your problem (because as I see it the issue is NOT in the ebean-jackson module but in Ebean WriteJson).

**Comment by rbygrave** [comment]
Test cases and fix pushed. Please check to see if that resolves the problem.

Cheers, Rob.

**Comment by icode** [comment]
Thanks a lot for pull! And how to break null value props ? set jackson mapper not availability

**Comment by icode** [comment]
@rbygrave How to break null value props on toJSON ? set jackson mapper not availability

**Comment by rbygrave** [comment]
*> How to break null value props on toJSON ?*

Hi, this statement is not clear.  Can you reference some Jackson
documentation for the feature you are wanting?  You might mean that you do
not want properties whose values are null to be included in the JSON
output.

Thanks, Rob.

**Comment by icode** [comment]
@rbygrave Yes, I not want properties whose values are null to be included in the JSON
output.I try to config Jackson `mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY)` but invalid.

**Comment by icode** [comment]
@rbygrave groups link https://groups.google.com/forum/#!topic/ebean/Z3aJ5cJ4brs

config Jackson mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY)

but wirte json : {"prop":null}

**Comment by rbygrave** [comment]
Ok, but this needs to go into a different ticket.

Cheers, Rob.

**Comment by icode** [comment]
different ticket? a new issue?

**Comment by rbygrave** [comment]
*> different ticket? a new issue?*

Yes and Yes.

This #276 ticket deals with 'transient' properties.  It has a unit test, is
fixed in HEAD and closed.    You are talking about a different issue ...
aka "how to suppress properties from JSON output when they have null values
" - that is a different issue to this one.

**Comment by icode** [comment]
Ok, thanks. Please check #280
