### ISSUE TITLE
SqlQuery setFirstRow fail - modify SQL using LIMIT/OFFSET etc to support firstRows/maxRows 

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#278]
Set the index of the first row of the results to return.

SqlQuery.setFirstRow(10) findList  return first row index 0

**Comment by rbygrave** [comment]
SqlQuery currently does not modify the SQL to add limit and offset or similar sql changes ... in order to support firstRows and maxRows.

I believe this is what you are asking for in this ticket.  To change SqlQuery such that it supports firstRows/maxRows by modifying the SQL (like the Orm queries).

I think that is a somewhat reasonable request/change. Modifying the SQL is relatively simple enough for the LIMIT OFFSET case (MySql, Postgres) but might be more problematic to implement when 'window function' is used (Oracle etc).  The big benefit of modifying the SQL is that it will generally be more performant (sometimes far more performant).

Assuming I have understand that correctly I'll adjust the title of this ticket to reflect the desired change.

**Comment by icode** [comment]
I think that is a somewhat reasonable request/change. I have a lot of other Sytem/Application table, like Stock , Industry and more 3rd table.I can't table refused to change, i can't build Model for table, so `Modifying the SQL is relatively simple enough for the LIMIT OFFSET case (MySql, Postgres) ` is need for me

**Comment by icode** [comment]
Please can quickly support SQL paging?

Thanks!

**Comment by rbygrave** [comment]
I don't know how quickly I can get to this.  Working on documentation at the moment etc.

**Comment by icode** [comment]
:cry: When fix it?

**Comment by rbygrave** [comment]
I'm not sure. There are various things ahead of this in terms of priorities but the list is getting smaller.  It should be sorted by the end of Jan.

**Comment by xxcode-monkey** [comment]
I also need such features , looking forward to an early solution

**Comment by icode** [comment]
+1 :+1:

**Comment by icode** [comment]
waiting this basic feature @rbygrave help!

**Comment by icode** [comment]
which Milestone fixed it? @rbygrave

**Comment by rbygrave** [comment]
It is not fixed. It is still open and no milestone associated.

**Comment by icode** [comment]
No restoration plan it?

**Comment by icode** [comment]
start at  23 Apr 2015, Going a year :sob:

**Comment by icode** [comment]
@rbygrave This has been forgotten?

**Comment by rbygrave** [comment]
No, its a case of complexity and priorities. 

That is, the people that pay the bills get to dictate the priorities largely (90%) and secondly this issue is more complex that it seems (in order to support Oracle etc) - those 2 issues have pushed it down the priority list.

**Comment by icode** [comment]
Excuse me, not arrange it?

**Comment by rbygrave** [comment]
I don't understand your last comment.  Can you expand it?

**Comment by icode** [comment]
Sorry, I see have doing this?

**Comment by rbygrave** [comment]
So the current plan for this issue is that I need to review Oracle's support for limit/offset (that came in with 12 I think?).  That is, I am not keen on this only working for Postgres/MySql (or at least it will cause a lot of pain if this is not supported on Oracle as well).

Will some luck I should get to this in the next 2 weeks.

**Comment by icode** [comment]
em, now orm padding not use for this?

**Comment by rbygrave** [comment]
I do not understand.

**Comment by icode** [comment]
Please fix, thanks

**Comment by icode** [comment]
this should use `com.avaje.ebean.config.dbplatform.SqlLimiter`, jdbc not support. current EBean Query can not use this ?

**Comment by rbygrave** [comment]
@icode When you post to a github issue that goes to all the watchers.
These tickets are not for the purpose of protracted discussions as that
effectively spams everyone trying to watch the project.

Discussions can take place on the google group forum. Move the discussion
there if you want.  The above sentence regarding "SqlLimiter, jdbc not
support" didn't make enough sense for me to understand. If you want to
explain that and take it further then please move the discussion to the
forum.

Thanks, Rob.

**Comment by rbygrave** [comment]
Closed at last eh.  For Oracle this presumes 12c and uses the sql2008 ANSI syntax. We don't really want to get into the business of parsing the sql to support row_number functions etc so I'm happy enough that this will do (and Oracle users have not been complaining about this anyway).
