### ISSUE TITLE
JndiDataSourceLookup assumes java: prefix

### ISSUE THREAD

**Issue by justinnichols** [ebean-orm/avaje-ebeanorm#298]
In an OSGi environment, such as Apache Karaf 3, the built-in JNDI feature uses osgi:service/ as a prefix when adding a JNDI registration.  Having Ebean assume all JNDI names will start with "java:" breaks the flexibility of having any name a developer desires.

Please fix it so that there is no assumption that the developer means "java:" (or "java:comp/env/jdbc/") simply because they omit it.  The developer should be aware of the lookup names in their environment.  This may be convenient for Tomcat containers, but is an issue for other environments.

To note: Apache Karaf's JNDI feature does provide a jndi:alias command to be able to define aliases for the registered JNDI name, however, at present that is a cumbersome workaround.

**Comment by justinnichols** [comment]
Addendum: I'm not positive that the workaround actually works.  When I manually added a JDNI alias in Apache Karaf, it prepends a slash, thus giving it the name: /java:comp/env/jdbc/foo.

**Comment by justinnichols** [comment]
Another Addendum: The workaround doesn't work because adding an alias makes it a javax.naming.Reference and not a javax.sql.DataSource.  Line 26 of JndiDataSourceLookup.java (in the lookup() method) typecasts with the assumption that the result from the ex.lookup() is of the DataSource type (thus throwing a ClassCastException):  DataSource ds = (DataSource)ex.lookup(jndiName);

**Comment by rbygrave** [comment]
I'll look to review this shortly.

**Comment by rbygrave** [comment]
Ok, I think we need to make this breaking change (remove the prepending behavior).  
I have posted the following to the google group to notify users of the upcoming change.

...
Hi JNDI DataSource users,

This change relates to issue https://github.com/ebean-orm/avaje-ebeanorm/issues/298

Currently Ebean will try to be 'helpful' when a JNDI DataSource name is used. Specifically if the name does not start with "java:" then Ebean will prepend "java:comp/env/jdbc/" to get the full JNDI name.

This behavior is potentially nice for Tomcat environments but unfortunately this 'helpful behavior' is a problem in OSGi environments.

As such, in the next release (4.7.1) we will remove this prepending behavior.  That means that everyone is expected to specify their JNDI DataSource name using the full name.

For example, instead of "mordor" we need to specify "java:comp/env/jdbc/mordor" instead.


I hope this does not inconvenience too many people.  Feedback welcome.



Cheers, Rob.

**Comment by rbygrave** [comment]
Change made as per the commit above.  From 4.7.1 the full JNDI name must be specified.
