### ISSUE TITLE
Why java.sql.Timestamp in mysql is datetime instead of timestamp?

### ISSUE THREAD

**Issue by qwIvan** [ebean-orm/avaje-ebeanorm#313]

**Comment by rbygrave** [comment]
Why do you think it should be Timestamp?  Do you have a problem with timezone issues?

**Comment by qwIvan** [comment]
I have an error in my SQL syntax "datetime(6)" when I use MySQL, and I change to postgresql to resolve it.

code from https://github.com/ebean-orm/avaje-ebeanorm-examples/blob/master/a-basic/src/main/java/org/example/domain/BaseModel.java

  @CreatedTimestamp
  Timestamp whenCreated;

  @UpdatedTimestamp
  Timestamp whenUpdated;

**Comment by rbygrave** [comment]
> SQL syntax "datetime(6)" 

I suspect that was due to the version of MySQL (older than 5.6 or something like that).

> Timestamp whenCreated;

The DDL type for java.sql.Timestamp depends on the database.  MySQL has a few options but I do think datetime is the best and for version 5.6 datetime(6) I think is the best type to use.

>  change to postgresql to resolve it.

I don't think you will regret moving to Postgres.


So I think you are all resolved then.

**Comment by qwIvan** [comment]
thanks, I resolve it with mysql 5.6.

**Comment by rbygrave** [comment]
Good.  I'll close this issue then.
