### ISSUE TITLE
[4.6.2] Cascade.ALL in @OneToMany with no effect? PostgreSQL doesn't allow DELETE of the parent

### ISSUE THREAD

**Issue by cdraeger** [ebean-orm/avaje-ebeanorm#321]
I am using Ebean together with Evolution in a Play project (Ebean is currently generating the SQL script). I have a parent with a `@OneToMany` relation to children:

```java
@Entity
@Table(name = "parents")
public class Parent extends Model {
  
  @PrivateOwned
  @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "parent")
  public final Set<Child> children = new HashSet<>();
}

@Entity
@Table(name = "children")
public class Child extends Model {
  
  @Required
  @ManyToOne(optional = false)
  @Column(name = "parent_id", nullable = false)
  public Parent parent;
}
```

Whenever a `Parent` is deleted, all children should be deleted too. However the Cascade-option doesn't seem to be used for the generated SQL-script. I just realized that by trying to delete a parent with children from the PostgreSQL database manually. I wasn't allowed to and got this error:

`ERROR: update or delete on table "parents" violates foreign key constraint "fk_childrens_parent_1" on table "children" Detail: Key (id)=(2) is still referenced from table "children".`

**Comment by rbygrave** [comment]
> However the Cascade-option doesn't seem to be used for the generated SQL-script.

In terms of DDL you are right, the DDL generated does not have any delete cascade on the foreign key  constraints.

So instead you should see multiple delete statements, 1 for the parent and another for the children.  So you should look at the generated sql delete statements and see that.

**Comment by cdraeger** [comment]
Hi, thanks for the answer, in code I am doing exactly that which is fine. I also know how to delete it manually, but I'd like to have the actual constraints in my DBMS as well. So I was wondering if this is a bug, or if there's a compelling reason not to carry the cascade over to the FK constraints when generating the script?

I'm probably switching of the script generation at the end of development anyway, so I guess I could include it in the script myself, but I wanted to make sure that this is not a bug (and if it is, report it).

**Comment by rbygrave** [comment]
*> but I'd like to have the actual constraints in my DBMS as well.*

Right. You basically can't do both in that ... if the DDL has delete
cascade on the fkeys then the DB will delete those children and in that
case the ORM should not *try* to delete them because it will fail with an
OptimisticLockException as the child rows are now not there.

So yes, you either get the DB to do the delete cascade or the ORM to but
not both.

So, what might be the reasons to get the ORM to do the delete cascade?
- If there is logical & actual deletes (not supported out of the box with
Ebean at the moment)
- If L2 cache is used then currently if the DB does delete cascade the
Ebean L2 cache is not notified with the specific changes (this probably
could be supported in the future but not at the moment)

Does that clarify things?

Cheers, Rob.

**Comment by cdraeger** [comment]
Ok that makes sense now, I guess I thought those cascade specifications were basically just used for generating the proper DDL so that the DBMS can handle it, not that the ORM itself uses them. Thanks, yes it clarifies things.

This can be closed then, just one question if you don't mind: if the reasons you mention don't apply to me (e.g. no Ebean L2 cache use), would you still for some reason advise against the DBMS doing the cascades when Ebean is used? I guess it's kind of a personal preference, I just seems cleaner to me to handle such constraints in the DB, so e.g. when the complete codebase is switched, all constraints would still be enforced (and maybe it's also more efficient). But anyway, thanks for clarifying!

**Comment by rbygrave** [comment]
*>  I just seems cleaner to me to handle such constraints in the DB, so
e.g. when the complete codebase is switched, all constraints would still be
enforced (and maybe it's also more efficient).*

My opinion yes I it seems 'cleaner' in that it is more 'declarative' (the
ORM / application code does less) which is usually good and yes I'd expect
it to be more efficient.

The caveat for me is that I generally want to be *able* to bring in L2
cache and I want to be *able* to bring in ElasticSearch ... even if I don't
think I need it initially.  Now technically Ebean could still update L2 &
ElasticSearch by just fetching the ids of all the beans that it knows will
be deleted before they are deleted ... it just does not support that at the
moment but it does most of this behavior already when we do a delete by id
so that might not be a bit enhancement to do.

The other downside would be that right now Ebean isn't going to generate
that DDL for you, I'll log an enhancement request for that.


Cheers, Rob.

**Comment by cdraeger** [comment]
Ok great, thanks again!
