### ISSUE TITLE
Model#update does not work with field access and mavenenhancer

### ISSUE THREAD

**Issue by io-levant** [ebean-orm/avaje-ebeanorm#370]
First of all **thanks** for all your hard work!

I have met some issues trying to update Models using field access. Basically if I have a Model like:

```java
public class User extends Model {
	@Id	public Long id;
	public String firstName;
}
```

and I (try to) update it using field access:

```java
User user = User.find.byId( userId );
user.firstName = "new glorious firstName";
user.update( );
```

Ebean says:

```
com.avaje.ebeaninternal.server.persist.DefaultPersister - Update skipped as bean is unchanged:ebean.domain.User@1
```

I noticed it with avaje-ebeanorm v. 4.7.3 and avaje-ebeanorm-mavenenhancer v. 4.5.3, I have no data for previous versions. Property access works fine.

I've put *very* simple demo project https://github.com/io-levant/test-ebean that can reproduce the error.

**Comment by io-levant** [comment]
I have just inspected the .class files in the /target folder, and at the line responsible for the field update:

```java
user.firstName = "new glorious firstName";
```

the bytecode is:

```
LINENUMBER 31 L2
ALOAD 5
LDC "new glorious firstName"
PUTFIELD ebean/domain/User.firstName : Ljava/lang/String;
```

May it be an enhancer's fault?

**Comment by rbygrave** [comment]
*> and I (try to) update it using field access:*
You are seeing expected behaviour in that there is no intention from an
Ebean perspective that setting a value via field access / putfield makes
the value dirty.

In short you could use markAsDirty() on the bean to force an update if you
want to pursue that path - that would be a valid approach.


*PlayFramework:*
You do see this type of code (field access - using putfield etc) in Play
framework examples and code. For that to work Play framework is using it's
own enhancement ... and replacing the putfield calls with calls to setter
methods (at least I'm pretty sure that is what they do but I haven't looked
at the bytecode yet). The point to note here is that all the *callers* need
their bytecode changed from putfields to setter method calls (you can't
achieve this via enhancement on the bean by itself).

*Complex types - JsonNode & Map:*
In Ebean some properties are almost 'exempt' from this dirty checking rule
- Map types for supporting storing JSON documents in the DB and Map for
Postgres HSTORE type are 2 examples along with Jacksons JsonNode (examples
in the x-postgres-features project).  So for the case of some complex types
(Map, JsonNode) Ebean can't be sure if they are dirty and must treat them
as dirty (so the side effect is that I'd recommend using Map over JsonNode
when you look to store JSON in the database as Ebean provides a map
implementation that has dirty checking support built into it).


*Properties in Java - Big picture:*As I understand it 'Properties' are not
coming to the Java language any time soon and for me this is a serious
proposition to consider another jvm language like Kotlin which comes with
properties support (and null safety and a bunch of other features).
Personally from an application development view (not so much
framework/library development) the features that Kotlin provides
(properties, null safety, extension methods,data classes) would improve a
lot of application code I have seen and still be great interoperability
with Java (easily consume Kotlin classes / code from Java code).


Hopefully that provides some explanation.


Cheers, Rob.

**Comment by rbygrave** [comment]
Closing this. Works as expected.

**Comment by io-levant** [comment]
Thanks, the explanation is totally fair, and I share the same feelings about Java properties not coming to the language (and the Kotlin general usefulness).

I think I misunderstood the docs, where they say that _"The class bytes are modified replacing the GETFIELD and PUTFIELD bytecode calls to "persistent fields" with method calls."_

I don't think that `markAsDirty` could solve the problem since any following update just updates the version and the updated fields (as per the JavaDoc).

**Comment by rbygrave** [comment]
*> I don't think that markAsDirty could solve the problem*
Right.  There is new feature to force update on all loaded properties (
https://github.com/ebean-orm/avaje-ebeanorm/issues/296) .. and this exists
on the transaction. So something more like that perhaps.
