### ISSUE TITLE
Remove diff "non flat mode" ... so diff going forward only supports flat mode 

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm#406]
So flat mode was the default and now it is the only option.

Removing from ServerConfig the method:

```java
  /**
   * Set to true if diff should return flat properties with dot notation rather than
   * embedded beans or reference beans (when the associated bean id is different).
   */
  public void setDiffFlatMode(boolean diffFlatMode) {
    this.diffFlatMode = diffFlatMode;
  }

```
... and removing the associated non flat mode diff.  Diff always in flat mode now.

**Comment by justinnichols** [comment]
I know I'm bringing up an old item here, but the Play Framework has updated to 2.5.x which brought in this change from Ebean (via a 3-major version jump) and has severely changed how we have to handle diffs now.  Given that we were relying on the non-flat version of the diff, can you provide a migration path to allow for that to still occur?  Or if not, would you mind letting us know why this change was necessary so we can at least understand it?

Thanks in advance.

**Comment by justinnichols** [comment]
It's kind-of a bad workaround (it relies on "id" to be the name of the @Id property), but I was able to get around this by the following (so please if you happen to know of a better way, I'd love to know, but given how we relied on the unflatted diff, this seems the best course of action without having to refactor many classes and/or lines of code):

```
package util;

import com.avaje.ebean.Model;
import com.avaje.ebean.ValuePair;

import java.util.HashMap;
import java.util.Map;

public class EbeanDiffUtil {
    public static Map<String, ValuePair> unFlattenDiff(Class rootClass, Map<String, ValuePair> diff) throws Exception {
        if (rootClass == null || diff == null) return null;
        if (diff.size() == 0) return diff;

        Map<String, ValuePair> returnMap = new HashMap<>();
        for (String s : diff.keySet()) {
            String[] props = s.split("\\.");
            // This requires the rootClass to have a property called id which is the @Id of the entity bean.
            //   - This is a poor convention, but a workaround for https://github.com/ebean-orm/avaje-ebeanorm/issues/406
            if (props.length > 1 && props[1].toLowerCase().equals("id")) {
                ValuePair valuePair = new ValuePair();

                Class beanType = getClassOfProperty(rootClass, props[0]);
                valuePair.setOldValue(getBeanById(beanType, diff.get(s).getOldValue()));
                valuePair.setNewValue(getBeanById(beanType, diff.get(s).getNewValue()));

                returnMap.put(props[0], valuePair);
            } else {
                returnMap.put(s, diff.get(s));
            }
        }

        return returnMap;
    }

    private static Class getClassOfProperty(Class rootType, String property) throws NoSuchFieldException {
        return rootType.getField(property).getType();
    }

    @SuppressWarnings("unchecked")
    private static Object getBeanById(Class beanType, Object id) {
        Model.Finder find = new Model.Finder(beanType);
        return find.byId(id);
    }
}
```

**Comment by rbygrave** [comment]
That getBeanById() method should change to return a reference bean.

```java
    @SuppressWarnings("unchecked")
    private static Object getBeanById(Class beanType, Object id) {
        // This find.byId() would hit the database every time ... 
        //Model.Finder find = new Model.Finder(beanType);
        //return find.byId(id);

        // ... use a reference bean instead
        return Ebean.getReference(beanType, id);
    }
```

**Comment by rbygrave** [comment]
> why this change was necessary so we can at least understand it?

The flattened diff was needed to support both @History  and @Changelog features.  The flattened diff I believe is much better at handling embedded beans and converting to JSON. At that point we had 2 modes for doing 'diff' and later on we get to the point of questioning why we would keep around the older diff mechanism.

I did ask the google group about changing the diff mode in July 2015 but there was not much reaction at that time. https://groups.google.com/forum/#!searchin/ebean/flat$20mode/ebean/n_1adkZdflk/0-mpRi1ueAgJ

I probably didn't communicate well when looking to drop the original diff mode (this ticket).  Given my previous conversations on the google group it seemed that the old diff mode could be dropped.

In general we want Ebean over time to deprecate and then remove deprecated features in order to keep the internals as simple and clean as possible.  I realise that didn't work so well for you wrt this feature being dropped.

**Comment by justinnichols** [comment]
Thanks for the explanation!  I'll test your code change suggestion tomorrow and make sure that it works well with how we're using it.

I think my main issue is that Play is upgrading very fast and we, as Play and Ebean users, are not getting informed by Lightbend of every fallout of this kind of upgrade.   The three major version upgrade of Ebean by Play is an enormous jump for a single dot-version of Play.  Couple that with the Play documentation lacking in a few places just allows these issues to occur for those who wish to perform the upgrades.

As for the google group, I'm subscribed but wasn't getting emailed _(though I will do so asap)_ so I didn't notice that topic.  I suspected you had good reason for this, only curious what the reason was _(which you kindly explained)_.  Unless it was a burden to keep a utility to allow an unflattened diff, I definitely would have suggested keeping an API that allowed the diff as such _(something like `Ebean.unflatDiff()` or some other better name)_.  Sadly I am too late to the game :)  The good news is that this workaround should work for now until we stop using Ebean.diff for what was originally intended in our code _(some developers previous to me were using it as a way to do field level validation to determine if a field was even allowed to be updated based on certain criteria, and I'd prefer the validation to be much more explicit than they had originally coded)_.

Thank you very much for your responsiveness on this.  I will keep a keen eye on the google group for Play and for Ebean.

**Comment by rbygrave** [comment]
No problem.

> as Play and Ebean users, are not getting informed by Lightbend of every fallout of this kind of upgrade

A while back I suggested to Ligthbend (was Play at the time obviously) that we could offer a combined support option but that idea was not supported (at least by James Roper at the time). The 2 projects operate independently with basically no cooperation  / communication and I don't think that will change. 

Things are a lot better with the newer PlayEbean plugin to allow people to upgrade Ebean versions more freely. That they locked developers into a old version of Ebean for so long ... yes, painful for many. Maybe we won't have this type of issue again.

Don't expect the Lightbend folks to know much about what is going on with Ebean. There is no regular  communication / connection there, they have never asked about where Ebean is going or and don't contribute to the Ebean project as such.

> I will keep a keen eye on the google group for Play and for Ebean.

Great. With Ebean we have pushed out a lot of versions over the last 9 months or so (with the help of sponsorship). That will slow down shortly but it's good to keep an eye on the changes and feedback as necessary etc.

Cheers, Rob.
