### ISSUE TITLE
SQL_LOGGER trace() to debug() issue - Unintelligible logging settings

### ISSUE THREAD

**Issue by XievenLonger** [ebean-orm/avaje-ebeanorm#412]
In com.avaje.ebeaninternal.server.transaction.JdbcTransaction

```Java
  @Override
  public boolean isLogSql() {
    return TransactionManager.SQL_LOGGER.isDebugEnabled();
  }
```
But in the same class
```Java
  @Override
  public void logSql(String msg) {
    TransactionManager.SQL_LOGGER.trace(Str.add(logPrefix, msg));
  }
```
So it is checked whether or not DEBUG on the SQL_LOGGER is enabled, but than the Sql is logged as TRACE.

In `com.avaje.ebeaninternal.server.query.CQueryEngine.logSql(CQuery<?>)` the SQL_LOGGER is also used - but directly checked whether or not TRACE is enabled - but than the logSql method of the transaction is used to actually log - that's somehow misleading and breaks the encapsulation.
```Java
  private void logSql(CQuery<?> query) {

    String sql = query.getGeneratedSql();
    // direct logger access
    if (TransactionManager.SQL_LOGGER.isTraceEnabled()) {
      sql = Str.add(sql, "; --bind(", query.getBindLog(), ")");
    }
    // encapsulated logger access
    query.getTransaction().logSql(sql);
  }
```

On a side note: Wouldn't it be better (and easier to understand) if there is __one__ logger (instead of the three loggers 'SQL', 'SUM' and 'TXN') which can than be set to TRACE (SQL), DEBUG (SUM) or INFO (TXN)?

**Comment by rbygrave** [comment]
Yes. Changing SQL_LOGGER.trace(...) to SQL_LOGGER.debug(...) as the fix for this issue.

> Wouldn't it be better (and easier to understand) if there is one logger 

There is utility value in having the separate loggers for Transactions and Summary logging as they really are for different purposes.  Suppressing the logging for commit of read only transactions for example is very useful. Similarly, control over the summary logging (around lazy loading / secondary query reviewing) so yes it is handy to have these as separate loggers.

>  TransactionManager.SQL_LOGGER.isTraceEnabled()

That is intended to only include the bind values into the SQL log at TRACE level. Not doing that can benefit people proving a lower cost sql log (less string appending, less bulk as bind values not included).  So there is a useful purpose there.
