### ISSUE TITLE
Enh info: @History support for H2 

### ISSUE THREAD

**Issue by ZeerDonker** [ebean-orm/avaje-ebeanorm#414]
Hello,

First off @rbygrave thank you for implementing the `@History` support for mysql https://github.com/ebean-orm/avaje-ebeanorm/issues/379 and postgresql. And thanks for the postgresql `@History` example.

Adding the following line to `/src/main/java/com/avaje/ebean/config/dbplatform/H2Platform.java` 
```
this.historySupport = new MySqlHistorySupport();
``` 
was the only line I needed to change in this library to support @History for the H2 database.

The `tstzrange` type wasn't supported in H2 memory database. (or at least in the H2 I was using)
Making a table like another table also wasn't supported, to make the history table. 
And instead of the sql triggers I used the `@PreUpdate` `@PreRemove` and `@PrePersist` annotations

**Comment by rbygrave** [comment]
> And instead of the sql triggers I used the @PreUpdate @PreRemove and @PrePersist annotations

Right. That is a pretty interesting point because it would be good to have @History support for H2 as that is the primary database for testing for a lot of people and would enable testing of the @History feature (and we all love H2 which is a second good reason).

Ok, so ideally we need a generic preUpdate and preDelete handler that just does the right thing.

Yes, this is a great idea. I'll ponder how to do the generic preUpdate/preDelete.

**Comment by rbygrave** [comment]
Right, I have done that and for the preUpdate/preDelete actually created a H2 DB Trigger.
java/com/avaje/ebean/config/dbplatform/H2HistoryTrigger.java

Using the DB trigger is good because we get all the columns inserted into the history for partial object updates and delete by id etc.
