### ISSUE TITLE
ENH: Add support for Removing ShutdownManager.shutdownHook ... manually control entire shutdown.

### ISSUE THREAD

**Issue by pycloux** [ebean-orm/avaje-ebeanorm#427]
Hi All,

I wonder if it could be possible to remove the automatic shutdownHook registration in the ShutdownManager.
I am using Ebean with Play 2.4 in a dependency injection managed configuration and having a shutdownHook prevent us to control correctly the lifecycle of the server.
I can understand the interest but I really think that it should be possible to "prevent" the shutdownHook registration.
Please, is it already possible ?

Regards,

PS: currently I created a class in the package "com.avaje.ebeaninternal.server.lib" in my own application to access the "protected" shutdownHook and "remove it".
This solve the issues but is rather ... crap :-)

**Comment by rbygrave** [comment]
> possible to "prevent" the shutdownHook registration.

A system property could be used to do that and this.

The alternative is to make the static method ShutdownManager.deregisterShutdownHook() public (from protected). Then you could just call that on startup.

In both cases it is then up to the application invoke ShutdownManager.shutdown() when desired in order to clean up resources.

**Comment by rbygrave** [comment]
It should be noted that when EbeanServer.shutdown() is called that automatically deregisters that server instance from the shutdown hook mechanism (com.avaje.ebeaninternal.server.lib.ShutdownManager) but this issue is really about the ShutdownManager which also has the responsibility for the "Ebean Container / SpiContainer" shutdown which typically means degistering from a cluster if present and shutdown of clustering resources (clustering networking etc).

**Comment by rbygrave** [comment]
Options to avoid the shutdown hook are:

Option 1:
```java
ShutdownManager.deregisterShutdownHook();
```

Option 2:
```java
   // set the system property before the Ebean container starts
   // or as a command line argument 
    System.setProperty("ebean.registerShutdownHook","false");
```
