### ISSUE TITLE
RawSqlParser doesn't seem to understand new lines directly after the SELECT keyword

### ISSUE THREAD

**Issue by spiltcoffee** [ebean-orm/avaje-ebeanorm#491]
The following test was written using ebean-orm/avaje-ebeanorm-examples/a-basic as the project:
```java
package main;

import com.avaje.ebean.Ebean;
import com.avaje.ebean.RawSql;
import com.avaje.ebean.RawSqlBuilder;
import org.example.domain.Customer;
import org.junit.Test;

public class RawSqlParserTest {

  @Test
  public void simple() {
    String sql = "SELECT\n  be_customer.name\nFROM\n  be_customer\nLIMIT 1";

    RawSql rawSql = RawSqlBuilder.parse(sql).create();
    Customer customer = Ebean
        .createQuery(Customer.class)
        .setRawSql(rawSql)
        .findUnique();
  }

}
```

This is the exception thrown when `.parse()` is called:
```
java.lang.RuntimeException: Expecting [SELECT
be_customer.name] to start with "select"

	at com.avaje.ebean.DRawSqlParser.trimSelectKeyword(DRawSqlParser.java:116)
	at com.avaje.ebean.DRawSqlParser.parse(DRawSqlParser.java:71)
	at com.avaje.ebean.DRawSqlParser.parse(DRawSqlParser.java:44)
	at com.avaje.ebean.RawSqlBuilder.parse(RawSqlBuilder.java:67)
	at main.RawSqlParserTest.simple(RawSqlParserTest.java:15)
```

It seems like `.trimSelectKeyword()` is assuming that there will always be a space character following the SELECT, which is not the assumption I was making about my queries.

**Comment by rbygrave** [comment]
So there are 2 ways to deal with this issue and I'm going to go with the approach that '\n' characters are replaced with ' ' (space) characters. The reason for taking this approach rather than allowing just dealing the the newline characters is that the logging of the SQL statements (org.avaje.ebean.SQL) is a bit yuk with the new line characters.

So replacing '\n' characters with ' ' (space) characters early means we fix the parsing issue and the resulting SQL if logged ... is nice and does not contain the newline chars.

**Comment by rbygrave** [comment]
Fixed, will be in the next release.
