### ISSUE TITLE
Upgrading to 6.13.5 causes "No suitable driver found for jdbc:mysql" error

### ISSUE THREAD

**Issue by koyabr** [ebean-orm/avaje-ebeanorm#508]
I used Ebean 6.9.1 in my previous project and it works fine. Now for a new project I upgrade to Ebean 6.13.5, and then I get "No suitable driver found for jdbc:mysql" error when I deploy my war and make first db access.

In `build.gradle` I wrote
```
compile('org.avaje.ebeanorm:avaje-ebeanorm:6.13.5')
runtime('mysql:mysql-connector-java')
```

In `ebean.properties` I have
```
datasource.default=mysql

datasource.mysql.username=xxx
datasource.mysql.password=xxx
datasource.mysql.databaseUrl=jdbc:mysql://localhost/xxx?characterEncoding=UTF-8
datasource.mysql.databaseDriver=com.mysql.jdbc.Driver
```

**Comment by rbygrave** [comment]
Can you include the full stack trace?  This does not seem like an Ebean issue but more a classpath issue.

**Comment by flqw** [comment]
Having the same problem, but for MS SQL with JTDS:

```
Caused by: java.sql.SQLException: No suitable driver found for jdbc:jtds:sqlserver://...
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.createUnpooledConnection(DataSourcePool.java:432)
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.createConnectionForQueue(DataSourcePool.java:665)
	at com.avaje.ebeaninternal.server.lib.sql.PooledConnectionQueue.ensureMinimumConnections(PooledConnectionQueue.java:227)
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.initialise(DataSourcePool.java:258)
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.<init>(DataSourcePool.java:226)

```

The only thing I changed is the maven dependency version (in this case 6.11.1 -> 6.14.1). The JTDS driver is present on the classpath (also as a maven dependency).

The config in the ebean properties file:

```
...
datasource.databaseUrl=jdbc:jtds:sqlserver://...
datasource.databaseDriver=net.sourceforge.jtds.jdbc.Driver
...
```

**Comment by flqw** [comment]
Looks like it is an classloader issue caused by https://github.com/ebean-orm/avaje-ebeanorm/issues/476

I am in a Spring environment, currently looking into it.

**Comment by rbygrave** [comment]
I wonder if it is https://github.com/ebean-orm/avaje-ebeanorm/issues/484 ?  ... maybe specific to the jdbc driver.

**Comment by rbygrave** [comment]
Are you able add ... Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver") ... before the DataSourcePool is initialised?

**Comment by rbygrave** [comment]
Sorry, in your case that should be ... Class.forName("net.sourceforge.jtds.jdbc.Driver");

**Comment by rbygrave** [comment]
@koyabr What specific version of the MySql jdbc driver are you using?  (mysql-connector-java)

**Comment by rbygrave** [comment]
Ok, looks like I can reproduce it using the MS SQL Server jdbc driver ... hold on.

**Comment by flqw** [comment]
@rbygrave You were right, adding

```
Class.forName("net.sourceforge.jtds.jdbc.Driver");
```

before creating the connection fixed it. The latest JTDS driver version is from 2013 and JDBC 3.0, so this explains it. Are there any drawbacks using such an old driver? I might consider switching to the official Microsoft driver, even if there is sadly no official maven dependency for it.

**Comment by rbygrave** [comment]
Ok good.  Unfortunately I mucked up my test and got a false positive so actually I haven't reproduced it just yet (but I'll look to do that with that JTDS driver) ... that said I'm reasonably confident this is the problem now which is:

Older JDBC 3 drivers that don't auto-register themselves will throw this SQLException: No suitable driver found

Q: Are there any drawbacks using such an old driver?

A: I really don't know (JTDS vs the MS driver).  In a way though it's not great if Ebean is forcing that decision on you so really I need to add that Class.forName() call back in so that people can use their older driver drivers (as there should be no negative side effects to having that  Class.forName() call there except that at some point in the future when everyone is jdbc4+ it is completely unnecessary).

Summary:
- I'm just going to confirm/reproduce
- I'll then look to add in that Class.forName() call ... and JDBC 3 drivers should be happy again.

**Comment by rbygrave** [comment]
I can reproduce this with JTDS 1.2.2  (and noted that it does not reproduce with 1.2.8 or 1.3.1 of the JTDS driver).

The "fix" is to add back in the Class.forName() on the driver. Effectively this confirms that this was a regression/bug introduced by #484 ... in that we still need to support JDBC3 drivers for a bit longer.
