### ISSUE TITLE
Column Constraint for Enum types should cover all Enum values in an inheritance hierachy

### ISSUE THREAD

**Issue by antonsarov** [ebean-orm/avaje-ebeanorm#513]
As discussed [here] (https://groups.google.com/d/topic/ebean/e1ogljqjQZE/discussion), there should be an option to customize the generated column constraint for Enum types.

**Detailed explanation:** If two classes share the same field name (the field is of type Enum) and both extend the same base class, then Ebean wrongly assumes that only the Enum values of the first class should be considered as constraints.

**Suggestion:** Ebean should detect such cases automatically and build a constraint which has all possible values (from all Enums).
**Alternative / extension:** The user should be able to configure which Enum values contribute to the constraint (this can be useful when the Enum values themselves have the same name - as we know that Ebean stores them as Strings).

**Comment by rbygrave** [comment]
As an example:

Thing is our superclass
Person extends Thing 
Vehicle extends Thing

Person has a PersonSize enum with SMALL, MEDIUM, LARGE ... and maps this to a DB column called 'size"
Vehicle has a VehicleSize enum with SMALL, HUGE ... and maps this to a DB column called 'size"

So the base table has a single column called "size" and it's check constraint should have SMALL, MEDIUM, LARGE and HUGE as constraint values.

You could argue/describe that we need to do this (combine the constraint values) due to the restriction of mapping the inheritance hierarchy into a single db table (rather than table per type etc which is not currently supported).
