### ISSUE TITLE
findPagedList() does not handle raw sql order by

### ISSUE THREAD

**Issue by chrstphrrbn** [ebean-orm/avaje-ebeanorm#660]
Upon updating to Play Framework 2.5 I stumbled upon this problem.

I have a query relying on database expression ordering ("year desc nulls last").

The issue #410, ment to avoid unexpected behaviour, does not take into account the fact that the RawSql might contain ordering.

The result is the order by from the raw sql is removed.

**Comment by rbygrave** [comment]
You need to provide an explicit example of what you are doing, and state what version of Ebean you are using.

**Comment by chrstphrrbn** [comment]
Sorry, I was interrupted before I could provide an example.

The version bundled with Play Framework 2.5.2 is 6.18.1.

The query in question is (simplified):
`
        RawSql rawSql =
                RawSqlBuilder
                        .parse("SELECT f.id, f.title, f.rating from film f order by f.rating desc nulls last")
                        .columnMapping("f.id", "id")
                        .columnMapping("f.title", "title")
                        .columnMapping("f.rating", "rating")
                        .create();

        Query<Film> query = Ebean.find(Film.class);
        query.setRawSql(rawSql);
`

Now, .findList() works as expected:
`SELECT f.id, f.title, f.rating from film f order by f.rating desc nulls last`
 *as long as* I don't add .setMaxRows() or setFirstRow() which renders:
`SELECT f.id, f.title, f.rating from film f order by f.id`

**Comment by rbygrave** [comment]
Q: What database platform are you using for this?

Note: I just updated your comment there using triple backtick java and triple backtick sql.

**Comment by chrstphrrbn** [comment]
Thanks for the layout fixes, I failed miserably.

I'm running:
Postgresql 9.4.2
JDBC driver: 9.4-1205-jdbc42

**Comment by rbygrave** [comment]
> Thanks for the layout fixes

No worries. Just a little trick with markdown that is good to know to
format blocks of code/sql etc.

Hopefully I get to look at this in the next day or so.

Cheers, Rob.

**Comment by rbygrave** [comment]
So I'm taking the specific issue here to be in BeanDescriptor.appendOrderById() ... that this does not take into account RawSql with an existing orderBy clause.

The fix is to include a check for and apply the orderBy clause from RawSql if it exists AND when the orderBy has not been overridden (as you are allowed to override the orderBy on a parsed raw sql query if you wish).

In addition: This particular use case uses a "nulls last" clause and that isn't supported in the current parsing of order by clauses so there is that additional fix to support that.
