### ISSUE TITLE
Q: Is there a plan to support @SqlInsert, @SqlUpdate @SqlDelete?  A: No

### ISSUE THREAD

**Issue by wenzhihong2003** [ebean-orm/avaje-ebeanorm#664]
1. has plan to supper @SqlInsert, @SqlUpdate @SqlDelete as it description in com.avaje.ebean.annotation.Sql

2. has plan to supper sql-Insert, sql-Update, sql-delete xml tag used in orm.xml or ebean-orm.xml

3. can show a full example of orm.xml or ebean.xml

**Comment by rbygrave** [comment]
> has plan to supper @SqlInsert, @SqlUpdate @SqlDelete as it description in com.avaje.ebean.annotation.Sql 

No. I'll remove that. This was a thought/plan to match some database API's I have seen in the past where for example all inserts/updates/deletes went via stored procedures.  Now in 2016, I haven't seen this for many years and in fact seen a push away from stored procedures.  With JDBC batch working better with prepared statements (rather than callable statements) and better database agnostic applications by reducing the use of stored procedures I don't see the need demand.

I'll remove those comments from @Sql.

So that removes the need for 2 and 3 as well.

**Comment by rbygrave** [comment]
I'll close this ticket on the basis that there is no longer any plan to add support for @SqlInsert, @SqlUpdate and @SqlDelete
