### ISSUE TITLE
SoftDelete does not delete row from cache

### ISSUE THREAD

**Issue by npokr** [ebean-orm/avaje-ebeanorm#685]
## Expected behavior
pass this test:
```
public void testDelete() throws Exception {
        User newUser = new User();
        newUser.setName("guest");
        service.insert(newUser);

        User guest = service.findByUsername("GUEST");
        assertNotNull(guest);
        service.delete(guest);

        guest = service.findByUsername("GUEST");
        assertNull(guest);
    }
```

## Actual behavior
Assertion fails - guest record is still in the cache.

### Steps to reproduce
Simplified class definition:
```
@Entity @Table(name = "users")
@CacheStrategy(naturalKey = "username", readOnly = true)
@Getter @EqualsAndHashCode(of = "username")
public class User implements UserDetails {
    @Id
    private Integer id;
    private String username;
    public void setUsername(String username) {
        this.username = null == username ? null : username.toLowerCase();
    }
    @SoftDelete
    private boolean deleted = false;
    @Version
    private Integer version;
}
```
Service code:
```
public User findByUsername(String username) {
        return getServer().find(getType()).setLoadBeanCache(true)
                .where().eq("username", username.toLowerCase()).findUnique();
}
```
With 7.6.1 this test is OK - there was one more line at PersistRequestBean.postDelete. Now this method's comment `Aggressive L1 and L2 cache cleanup for deletes ` became incorrect.

**Comment by rbygrave** [comment]
The issue here is that there is a significant difference between "near cache" based caching and "distributed cache" based caching (like Hazelcast, Ignite etc).

That is, the cost of invalidating distributed caches (Hazelcast, Ignite etc) is relatively speaking much higher and for a large transaction that performs a lot of changes the cost of performing the cache invalidation in the foreground thread impacts the normal response time.

As such, the cache invalidation for deletes was also moved into background processing.

If for example you modify your test to include a wait time of a few millis you will find that the invalidation occurs (as the background thread running the invalidation gets a chance to execute).

You don't state what version you are using or the exact method that comment about aggressive deletes relates to.

So at this stage, no this is not a bug.  Add some sleep time into your test before the second query.

**Comment by npokr** [comment]
> If for example you modify your test to include a wait time of a few millis you will find that the invalidation occurs
I put `Thread.sleep(10000);` between delete and get from cache, but deleted record remains in cache. Maybe commit needed? My test extends AbstractTransactionalTestNGSpringContextTests, so all tests rolled back...

> You don't state what version you are using or the exact method that comment about aggressive deletes relates to
Version 7.8.1, method `PersistRequestBean.postDelete`.

**Comment by rbygrave** [comment]
> Maybe commit needed? 

Yes. The cache invalidation fires after a successful commit (and the cache delete invalidation has moved into there now so yes you need the commit) .

> PersistRequestBean.postDelete.

Thanks. I'll look at that comment.
