### ISSUE TITLE
History Many-To-Many Lazy-Loads fail

### ISSUE THREAD

**Issue by flqw** [ebean-orm/avaje-ebeanorm#782]
I have an issue regarding many-to-many relationships in combination with history tables and lazy-loads. I have a Postgresql Schema set up with additional history tables and views for both the origin (A) and target (B) entity as well as the mapping table between A and B. If I query A with the following query:

```java
Ebean.find(A.class).asOf(timestamp).findList();
```

and then access the List\<B\> property of A the following query is generated:

```sql
select [...] 
from b_with_history t0 
left outer join a_b_with_history int_ 
on int_.b_id = t0.id 
and int_.sys_period @> ?::timestamptz 
where t0.sys_period @> ?::timestamptz
and (int_.a_id) in (?)
```

and the following error happens:

```
org.postgresql.util.PSQLException: No value specified for parameter 3.
```

because the second asOf timestamp bind value is missing:

```
Bind values:[asOf 2016-07-22 09:40:44.437, 1] 
```

The query itself does work correctly if I try it manually and set all three values. So it seems it is an issue related to the binding.

The exception does **not** happen if I fetch the List\<B\> eagerly by adding ``.fetch("bs")`` to the query and everything is done in one query.

**Comment by rbygrave** [comment]
> because the second asOf timestamp bind value is missing:

Yes that is correct. 

The issue here is internally Ebean is increments a counter on the query for the number of "as of" tables used.  The join to the intersection (which has history) does not increment that counter when we need it to.

This is fixed in `SqlTreeNodeRoot.addAsOfTableAlias()` by checking the `lazyLoadParent` property and doing `query.incrementAsOfTableCount();` when required.
