### ISSUE TITLE
HistoryExclude Many-to-Many Query-Generation Error

### ISSUE THREAD

**Issue by flqw** [ebean-orm/avaje-ebeanorm#783]
I found an error regarding the query-generation with @HistoryExclude annotated Relationships in an entity.

The following relationship exists in entity A:

```java
@HistoryExclude
@ManyToMany(mappedBy = "as")
private List<B> bs;
```

And this query:

```java
Ebean.find(A.class).fetch("bs").asOf(timestamp).findList();
```

results in the following sql query for the relationship:

```sql
select [...]
from b_with_history t0 -- WRONG!
left outer join a_b int_ on int_.b_id = t0.id
where (int_.a_id) in (?)
```

and throws the exception

```
Query threw SQLException:ERROR: relation "b_with_history" does not exist
```

because ``b_with_history`` does not exist, as b is not an history entity and therefor marked with @HistoryExclude in A.

**Comment by rbygrave** [comment]
Note regarding internals.  The issue here is around SqlTreeNodeRoot.appendFromBaseTable() ... which uses  `desc.getBaseTable(temporalMode)`.  The effective bug is that BeanDescriptor.getBaseTable(temporalMode) method used the value of baseTableAsOf with the history name (when the bean does not have history ... although the intersection table to the bean does have history).

So the effective fix applied here fixes the baseTableAsOf value returned from  `DeployBeanDescriptor.getBaseTableAsOf()`.
