### ISSUE TITLE
How to sort results by _score when using ebean with elasticsearch?

### ISSUE THREAD

**Issue by wei-hai** [ebean-orm/avaje-ebeanorm#795]
I tried using orderBy("_score desc") but it doesn't work. Any suggestion?
The code piece looks like:

PagedList<T> obj = T.find.where()
                .multiMatch(query,"key1","key2","key3")
                .setMaxRows(5)
                .orderBy("_score desc")
                .setUseDocStore(true)
                .findPagedList();

**Comment by rbygrave** [comment]
Hi,

With Ebean we have the policy of wanting questions to be posted to the google group forum at:
https://groups.google.com/forum/#!forum/ebean

This policy is stated at: http://ebean-orm.github.io/support

The reason for the policy is because protracted questions / discussions on github effectively spam the "watchers" (and we want to encourage people to watch the project and get a high quality stream of code changes).

Can you please post your question to https://groups.google.com/forum/#!forum/ebean

Thanks, Rob.
